### ISSUE TITLE
[FEATURE] FOCUS TIMER

### ISSUE THREAD

**Issue by tuanngo1001** [tuanngo1001/tubtrunk#1]
**User stories:**

- [x] As a user, I want to start the focus timer so that I can proceed with my work/study. #2 
- [x] As a user, I want to view the timer progress so that I can know how long I have focused. #3 

- [x] As a user, I want to stop the timer so that I can take a break. #10 

- [x] As a user, I want to get a notification when my focus time ends so that I know I am finished. #14 

- [x] As a user, I want the timer to reset after I switch to another application on my phone so that the application knows I break my commitment. #4 

**Acceptance Criteria:**
- The code is tested and passes all tests.
