### ISSUE TITLE
[USER] As a user, I want to stop the timer so that I can take a break.

### ISSUE THREAD

**Issue by thain-gd** [tuanngo1001/tubtrunk#10]
**Points**: 1.0

**Related to feature** #1 

**Tasks**

- [x] Stopping the timer stops the count and the animation
- [x] Have reset button to restart the timer with the same selected duration

**Acceptance criteria**

- [x] Given that I have started the timer and I'm in the middle of a session, when I click Stop, the countdown should pause
