### ISSUE TITLE
[USER] As a user, I want to see the rewards' requirements so that how to get them.

### ISSUE THREAD

**Issue by QuocViNguyen** [tuanngo1001/tubtrunk#11]
**Task**:

- [x] Create the rewards section UI
- [x] Add stub Database to fetch the rewards' requirements to display to the user
- [x] Create a model class to store the reward's requirements
- [x] Create a controller class to get all the rewards' requirements

**Points**: 2.0

**Related to feature** #5 

Acceptance Criteria:
- Given the user is logged in,
when they tap on Missons tab, user is able to see how to pass each mission.
