### ISSUE TITLE
[USER] As a user, I want to get a notification when my focus time ends so that I know I am finished.

### ISSUE THREAD

**Issue by thain-gd** [tuanngo1001/tubtrunk#14]
**Points**: 0.5

**Related to feature** #1 

**Task**:

- [x] Create Notification Controller
- [x] Link the Controller with the timer page view
- [x] Create the notification page

**Acceptance criterias**

- [x] Given that I'm at the Timer page, when the countdown finishes, I should receive a pop up notifying me that I have completed the session
