### ISSUE TITLE
[USER] As a user, I want to view the community leaderboard.

### ISSUE THREAD

**Issue by tuanngo1001** [tuanngo1001/tubtrunk#16]
**Points: 2**
Related to feature #12 
**Task**:

- [x] Create a leaderboard button on the Account tab
- [x] Create a page for the leaderboard and link it from the button
- [x] Fetch all users from the database and display it on the leaderboard page

Acceptance Criteria:
- Given the user clicked on the leaderboard button on the account page, when the leaderboard page shows up, then it shows the leaderboard  on the page
