### ISSUE TITLE
[USER] As a user, I want to view the history of all my focus sessions

### ISSUE THREAD

**Issue by trun-g** [tuanngo1001/tubtrunk#19]
**Point**: 2.0

**Related to feature** #6 
**Task**:

- [x] Create a History tab
- [x] Display all the focus sessions on the History tab in descending order

**Acceptance Criteria:**

- [x]  Given that user is at statistic page, when user click to history tab, the history list of all focus sessions should show up.

**Comment by tsonga12** [comment]
Close this in #66
