### ISSUE TITLE
[USER] As a user, I want to start the focus timer so that I can proceed with my work/study.

### ISSUE THREAD

**Issue by thain-gd** [tuanngo1001/tubtrunk#2]
**Points**: 3.0

**Related to feature** #1 

**Tasks**

- [x] Start with default duration if no duration is selected
- [x] If duration is selected, start with new duration

**Acceptance criterias**

- [x] Given that I am at the Timer page, when I click the Start button, the timer should start the countdown
