### ISSUE TITLE
[USER] As a user, I want to view averages and other statistics of my focus sessions

### ISSUE THREAD

**Issue by trun-g** [tuanngo1001/tubtrunk#22]
**Point**: 2.0

**Related to feature** #6 
**Task**:

- [x] Create a method from the controller class to calculate the average focus times in minutes
- [x] Display the calculated average focus times under the total focus times section 

**Acceptance Criteria:**
- [x] Given that user is in statistic page, when user have many previous focus sessions done, the page should display the average of user's focus sessions.

**Comment by tsonga12** [comment]
Close this in #66
