### ISSUE TITLE
[USER] As a user, I want to view a summary on success/failure rates of my focus sessions

### ISSUE THREAD

**Issue by trun-g** [tuanngo1001/tubtrunk#23]
**Points**: 1.5

**Related to feature** #6 

**Task**:

- [x] Create Statistics section UI
- [x] Add DB script to fetch focus sessions of the user
- [x] Create a model class to store data of focus sessions
- [x] Create a controller class to calculate success/failure rates from data and send the result to UI with a pie chart
