### ISSUE TITLE
[USER] As a user, I want to view the timer progress so that I can know how long I have focused.

### ISSUE THREAD

**Issue by thain-gd** [tuanngo1001/tubtrunk#3]
**Points**: 1.0

**Related to feature** #1 

**Task**

- [x] Timer counts down to 0 with visual indication
- [x] Timer resets when reaches 0

**Acceptance criterias**

- [x] Given that I am at the Timer page, when I click Start, the remaining duration should be displayed
