### ISSUE TITLE
[USER] As a user, I want to reset after I switch to another application on my phone so that the application knows I break my commitment.

### ISSUE THREAD

**Issue by QuocViNguyen** [tuanngo1001/tubtrunk#4]
**Points**: 2.5

**Related to feature** #1 

**Tasks:**
- [x] Add WidgetsBindingObserver
- [x] Change notification due to state
- [x] Push notification for app switching

**Acceptance criterias**
- [x] Given that I am in the middle of a session, when I close the app, I will be assessed a fail for the current session
