### ISSUE TITLE
[FEATURE] Reward System

### ISSUE THREAD

**Issue by tuanngo1001** [tuanngo1001/tubtrunk#5]
**User stories:**
- [x] As a user, I want to receive my reward after the focus time so that I will have the motivation to use the application. #7 

- [x] As a user, I want to check available reward challenges to earn more rewards. #9 

- [x] As a user, I want to see the rewards' requirements so that I know the way to get them. #11 
- [x] As a user, I want to view items in the store and buy with my rewards. #30
