### ISSUE TITLE
[FEATURE] Statistic

### ISSUE THREAD

**Issue by tuanngo1001** [tuanngo1001/tubtrunk#6]
**User stories:**
- [x] As a user, I want to view the history of all my focus sessions #19 

- [x] As a user, I want to view a summary on success/failure rates of my focus sessions #23 

- [x] As a user, I want to view the average of my focus time #22 

**Acceptance Criteria:**
- The code is tested and passes all tests.

**Comment by tsonga12** [comment]
Finish off Statistic feature
