### ISSUE TITLE
[FEATURE] Networking

### ISSUE THREAD

**Issue by tuanngo1001** [tuanngo1001/tubtrunk#8]
**User stories:**
- [x] As a user, I want to log in with my account. #13

- [x] As a user, I want to sign up with new account. #15 

- [x] As a user, I want to log/sign out. #18 

- [x] As a user, I want to share my rewards. #20 

- [x] As a user, I want to share my progress statistic. #21 

**Acceptance Criteria:**
- The code is tested and passes all tests.
